### ISSUE TITLE
How many bases are in the expression model?

### ISSUE THREAD

**Issue by AaboutL** [ascust/3DMM-Fitting-Pytorch#29]
https://github.com/ascust/3DMM-Fitting-Pytorch/blob/8ca87fc3ce42555d376dc505858e96536068896d/convert_bfm09_data.py#L46
hi,
Dose this line of code mean that there are 79 bases contained in the FaceWarehouse expression model?
In some other projects, I find that they just use 29 expression bases.
I want make sure that how many bases are in the FaceWarehouse expression model, since I can not get the origin model from the FaceWarehouse website.
I am Looking forward for your reply.
Thanks.

**Comment by ascust** [comment]
Sorry for the late reply cuz I have been a bit busy. I am not really sure about the original model. But the code does mean it has 79 bases. and that it does make sense to use a subset of the bases (say 29), because only the first several bases play an important role. There are the principle components from PCA.
